//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySchoolProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int Id { get; set; }
        public string AspNetUserId { get; set; }
        public int CoursesId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Courses Cours { get; set; }
    }
}
